# Generated by Django 4.1.6 on 2023-02-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("RIDER", "Rider"), ("DRIVER", "Driver")],
                default="RIDER",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
