# Generated by Django 4.1.6 on 2023-03-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("RIDER", "Rider"), ("DRIVER", "Driver"), ("NONE", "None")],
                default="RIDER",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
