# Generated by Django 4.1.6 on 2023-06-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0004_alter_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rider",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("authentication.user",),
        ),
    ]
