# Generated by Django 4.1.6 on 2023-02-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_type"),
        ("rider", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Rider",),
        migrations.CreateModel(
            name="Rider",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("authentication.user",),
        ),
    ]
