# Generated by Django 4.1.6 on 2023-06-26 16:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rider", "0001_initial"),
        ("driver", "0005_alter_driver_cartype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_start", models.DateField(auto_created=True)),
                ("time_completed", models.DateField(default=None)),
                ("duration", models.TimeField(default=None)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("ONGOING", "Ongoing"),
                            ("NA", "Na"),
                        ],
                        default="NA",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("origin", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "destination",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_trips",
                        to="driver.driver",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_trips",
                        to="rider.rider",
                    ),
                ),
            ],
        ),
    ]
