# Generated by Django 4.1.6 on 2023-06-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0003_auto_20230603_2047"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="carType",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("LUXURY", "Luxury")],
                default="NORMAL",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
