# Generated by Django 4.1.6 on 2023-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0004_driver_cartype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="carType",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("LUXURY", "Luxury")],
                default="NORMAL",
                max_length=20,
                verbose_name="CarType",
            ),
        ),
    ]
