# Generated by Django 4.1.6 on 2023-03-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_auto_20230322_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='occupied_status',
            field=models.BooleanField(default=False),
        ),
    ]
